version: '2'
services:
  wordpress:
    scale: ${SCALE}
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ${DOMAIN}
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreateOnQuorum
      request_line: GET / HTTP/1.0
  wordpress-data:
    scale: 1
    start_on_create: true
  db:
    scale: 1
    start_on_create: true
  filebeat:
    scale: 1
    start_on_create: true
